INSERT INTO TB_MENU
VALUES (SEQ_MENU_ID.NEXTVAL, '메뉴1', 10, 10, 10, 'RICE');
INSERT INTO TB_MENU
VALUES (SEQ_MENU_ID.NEXTVAL, '메뉴2', 15, 10, 20, 'SOUPS');

INSERT INTO TB_MEMBER
VALUES (SEQ_MEMBER_ID.NEXTVAL, 'test_1@gmail.com', '$2a$10$MZ.4QKiC2Ruo2JcfYxIWAuepOGYB6vgG42lT6vrgdW7ZAwk5a46aO', '뽀리', 'F', sysdate, '010-1234-5678', sysdate, 'N');
INSERT INTO TB_MEMBER
VALUES (SEQ_MEMBER_ID.NEXTVAL, 'test_2@gmail.com', '$2a$10$MZ.4QKiC2Ruo2JcfYxIWAuepOGYB6vgG42lT6vrgdW7ZAwk5a46aO', '재롱이', 'M', sysdate, '010-1111-2222', sysdate, 'N');
INSERT INTO TB_MEMBER
VALUES (SEQ_MEMBER_ID.NEXTVAL, 'test_3@gmail.com', '$2a$10$MZ.4QKiC2Ruo2JcfYxIWAuepOGYB6vgG42lT6vrgdW7ZAwk5a46aO', '가나', 'M', sysdate, '010-1311-2222', sysdate, 'N');
INSERT INTO TB_MEMBER
VALUES (SEQ_MEMBER_ID.NEXTVAL, 'test_4@gmail.com', '$2a$10$MZ.4QKiC2Ruo2JcfYxIWAuepOGYB6vgG42lT6vrgdW7ZAwk5a46aO', '다라', 'F', sysdate, '010-1611-2222', sysdate, 'N');
INSERT INTO TB_MEMBER
VALUES (SEQ_MEMBER_ID.NEXTVAL, 'test_5@gmail.com', '$2a$10$MZ.4QKiC2Ruo2JcfYxIWAuepOGYB6vgG42lT6vrgdW7ZAwk5a46aO', '마라마', 'F', sysdate, '010-1811-2222', sysdate, 'N');

INSERT INTO TB_BLOG
VALUES (SEQ_BLOG_ID.NEXTVAL, 1, '저는 뽀리입니다. 꽤 귀엽구요\n잘 부탁합니다.', 120);
INSERT INTO TB_BLOG
VALUES (SEQ_BLOG_ID.NEXTVAL, 2, '저는 재롱이입니다. 굉장히 싸납구요\n조심하세요.', 57);
INSERT INTO TB_BLOG
VALUES (SEQ_BLOG_ID.NEXTVAL, 3, '저는 담비입니다.\n구운게 아니라 원래 색깔입니다.', 1000);
INSERT INTO TB_BLOG
VALUES (SEQ_BLOG_ID.NEXTVAL, 4, '저는 환희입니다. \n항상 감사하구요.\n주인만 물어요.\n센척 엄청합니다.', 650);

INSERT INTO TB_MEMBER_DETAIL
VALUES (1, 164, 66);
INSERT INTO TB_MEMBER_DETAIL
VALUES (2, 170, 70);
INSERT INTO TB_MEMBER_DETAIL
VALUES (3, 181, 85);
INSERT INTO TB_MEMBER_DETAIL
VALUES (4, 155, 45);
INSERT INTO TB_MEMBER_DETAIL
VALUES (5, 168, 70);

INSERT INTO TB_FOLLOW
VALUES (2, 1);
INSERT INTO TB_FOLLOW
VALUES (3, 1);
INSERT INTO TB_FOLLOW
VALUES (4, 1);
INSERT INTO TB_FOLLOW
VALUES (1, 2);
INSERT INTO TB_FOLLOW
VALUES (1, 3);
INSERT INTO TB_FOLLOW
VALUES (1, 4);

-- 운동 공공데이터 (CSV)
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '108배', 2, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, 'AB 롤아웃', 8, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, 'TRX 운동', 7, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, 'wty운동', 7, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, 'W익스텐션', 4, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '걷기', 3, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '검도', 6, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '게이트볼', 3, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '계단내려가기', 3, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '계단오르기', 8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '고블릿 스쿼트', 5.5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '고전무용', 6, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '고정식 자전거', 5.5, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '골프', 4.8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '국민체조', 3.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '권투펀칭', 6, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '기체조', 4.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '낚시', 3, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '난타', 3.8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '노르딕워킹', 6, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '농구슈팅 연습', 4.5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '농구시합', 8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '다이어트 댄스', 4.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '다트', 2.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '달리기', 7, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '당구', 2.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '대청소', 3, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '댄스스포츠', 5.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '덤벨 바디 로테이션', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '덤벨 숄더프레스', 5.5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '덤벨 프레스', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '덤벨 플라이', 5.5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '덩키킥', 7, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '데드 리프트', 5.5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '데드버그', 4, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '뒤로 걷기', 3, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '등산', 7, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '디스코 댄스', 7.8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '딥스', 5.5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '뛰기', 7, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '라인댄스', 7.8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '라켓볼연습', 7, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '러시안트위스트', 4, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '런닝', 7, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '런닝머신', 6, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '런지', 3.8, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '레그 레이즈', 5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '레그 익스텐션', 5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '레그 컬', 5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '레그 킥 백', 5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '레그 프레스', 5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '레터럴 레이즈', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '레프팅', 5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '렛풀다운', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '로드바이크', 8.5, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '로프운동', 6, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '루마니안 데드리프트', 5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '리버스 컬', 5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '리버스 팩 덱 플라이', 4, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '마라톤', 9, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '마운틴 클라이머', 7, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '마이마운틴', 5.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '맨발걷기', 4.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '맨손 줄넘기', 7, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '모던댄스', 4.8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '모래주머니 차고 걷기', 6.8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '바벨 숄더프레스', 5.5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '바벨 스쿼트', 6, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '발레', 5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '방송댄스', 7, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '배구연습', 4, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '배드민턴', 4.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '백 스쿼트', 6, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '백 익스텐션', 3.5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '밸리댄스', 4.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '버드독', 3.8, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '버피테스트', 7, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '번지피지오', 5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '벤치 프레스', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '벤치딥스', 3, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '벤트 오버 레터럴 레이즈', 5.5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '벤트 오버 바벨 로우', 5.5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '벽 스쿼트', 5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '복근운동', 3.8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '복싱', 7.8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '볼링', 3, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '브릿지', 3.5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '빠르게 걷기', 6, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '사이드 런지', 5.5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '사이드 레그레이즈', 4, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '사이드 레터럴 레이즈', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '사이드 밴드', 3.5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '사이드 크런치', 4, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '사이드 플랭크', 3.8, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '사이클론', 7, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '산악자전거', 8.5, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '산책', 4, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '산행', 4, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '살사댄스', 4.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '새천년체조', 3.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '세차', 3, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '수상스키', 6, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '수영(IM)', 8, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '수영(배영)', 8, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '수영(자유영)', 6.1, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '수영(접영)', 11, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '수영(평영)', 5.3, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '수중 에어로빅', 4, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '스케이팅', 7, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '스쿼시', 12, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '스쿼트', 5.5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '스쿼트 덤벨 프레스', 7, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '스크린골프', 4, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '스키', 6, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '스키머신', 6.8, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '스탠딩 카프 레이즈', 5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '스텝밀', 7, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '스텝박스', 5.5, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '스티프 레그 데드리프트', 8, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '스포츠댄스', 5.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '스포츠클라이밍', 7, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '스플릿 스쿼트', 5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '슬로우버피', 5.5, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '승마', 5.8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '시티드 니업', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '시티드 로우', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '실내 스케이팅', 7, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '실내 자전거', 5.5, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '씨름', 6, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '아령들기', 5.5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '아이스하키', 8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '아쿠아로빅', 4, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '악력기 운동', 1.3, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '앉아서 다리들기', 2.5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '암벽등반', 11, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '암워킹', 6, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '암풀다운', 4, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '야구 캐치볼', 2.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '양팔벌려 제자리 뛰기(PT체조)', 3, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '어시스트 풀업', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '에어로빅', 6.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '에어로빅', 6, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '와이드 스쿼트', 5.5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '와일드 런지', 5.5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '요가', 2.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '운동장 걷기', 4.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '워킹', 4.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '워킹런지', 5.5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '원 암 덤벨로우', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '월볼샷', 6, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '윈드서핑', 5, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '윗몸일으키기', 3.8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '유도', 10, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '유연체조', 3.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '이두 컬', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '인라인스케이트', 5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '인클라인 벤치 프레스', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '인터벌 런닝', 8, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '일립티컬', 6, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '자유수영', 6, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '자전거', 7, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '재즈댄스', 4.8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '재즈사이즈', 6, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '점프 버피테스트', 8.5, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '점프 스쿼트', 6, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '점핑운동', 4.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '제기차기', 3, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '제자리 걷기', 2, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '제자리뛰기', 5.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '조깅', 7, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '조정(로잉머신)', 4.8, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '족구', 5.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '주짓수', 5.3, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '줄넘기', 8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '줌바댄스', 5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '짐볼운동', 3.8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '천국의계단', 8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '철봉매달리기', 3.8, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '체스트 프레스', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '축구 프리킥 차기', 7, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '축구시합', 10, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '축구연습', 7, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '컨벤셔널 데드리프트', 8, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '케이블 크로스 오버', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '케틀벨', 5.5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '크런치', 5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '크로스 크런치', 4.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '크로스 핏', 8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '킥 백', 5, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '킥복싱', 10, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '탁구', 4, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '태권도', 10, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '태극권', 4, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '태보', 7, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '탱고', 5.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '턱걸이', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '테니스', 7, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '트라이셉스 익스텐션', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '트라이셉스 푸시 다운', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '트래킹', 5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '트랙걷기', 4.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '트램폴린', 4.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '트위스트 댄스', 4.8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '트위스트 런', 5, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '파워워킹', 6, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '파크골프', 4.3, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '팔굽혀펴기', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '패들보드', 6, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '팩 덱 플라이', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '펙덱 플라이', 5.5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '펜싱', 6, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '포크댄스', 7.8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '폴댄스', 5.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '폼롤러', 3, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '푸쉬업', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '풀 스쿼트', 6, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '풀업 - 상지(어깨)', 3.8, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '풀업(턱걸이)', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '풋살', 8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '프론트 레이즈', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '프론트 풀다운', 4, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '프리다이빙', 7, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '프리테니스', 7, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '플라멩고', 4.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '플랭크', 3.8, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '플로터킥', 5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '필라테스', 5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '하이킹', 6, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '하프마라톤', 9, 'CARDIO');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '할로우 보디홀드', 3, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '해머 컬', 5, 'UPPER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '행잉 레그레이즈', 10, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '훌라후프', 5.5, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '훌라후프', 4, 'LIFE');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '힙 쓰러스트', 6, 'LOWER');
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (SEQ_EXERCISE_ID.NEXTVAL, '힙 어브덕션', 5, 'LOWER');

INSERT INTO TB_POST
VALUES (SEQ_POST_ID.NEXTVAL, '인생 첫 바디프로필', '이번에 5개월 동안 식단과 운동을 병행하여 인생에서 처음으로 바디프로필을 찍어봤습니다.', DEFAULT, SYSDATE, 1);
INSERT INTO TB_POST
VALUES (SEQ_POST_ID.NEXTVAL, '두번째 바디프로필은 할만 하네', '두번째라고 식단과 운동을 하는것에는 어렵지 않았는데, 운동에 대한 회의감을 견디는게 조금 힘들었습니다.', DEFAULT, SYSDATE, 1);
INSERT INTO TB_POST
VALUES (SEQ_POST_ID.NEXTVAL, '20년만에 처음 다이어트', '19살까지 살이 찌지 않다가 20살때 급격히 식욕이 늘어나면서 10kg이 증가하였습니다.', DEFAULT, SYSDATE, 2);
INSERT INTO TB_POST
VALUES (SEQ_POST_ID.NEXTVAL, '부산 해운대 가자', '이번 부산 해운대에서 선팅을 하기 위해서 몸을 만들기 시작했습니다.', DEFAULT, SYSDATE, 2);

INSERT INTO TB_IMAGE
VALUES (SEQ_IMAGE_ID.NEXTVAL, '식단 1일차.JPG', '1.JPG', 3);
INSERT INTO TB_IMAGE
VALUES (SEQ_IMAGE_ID.NEXTVAL, '식단 2일차.JPG', '2.JPG', 3);
INSERT INTO TB_IMAGE
VALUES (SEQ_IMAGE_ID.NEXTVAL, '헬스장.JPG', '3.JPG', 3);
INSERT INTO TB_IMAGE
VALUES (SEQ_IMAGE_ID.NEXTVAL, '식단.JPG', '4.JPG', 4);
INSERT INTO TB_IMAGE
VALUES (SEQ_IMAGE_ID.NEXTVAL, '헬스장.JPG', '5.JPG', 4);
INSERT INTO TB_IMAGE
VALUES (SEQ_IMAGE_ID.NEXTVAL, '헬스장1일차.JPG', '6.JPG', 2);
INSERT INTO TB_IMAGE
VALUES (SEQ_IMAGE_ID.NEXTVAL, '부산해운대.JPG', '7.JPG', 1);
INSERT INTO TB_IMAGE
VALUES (SEQ_IMAGE_ID.NEXTVAL, '파라솔.JPG', '8.JPG', 1);

INSERT INTO TB_REPLY
VALUES (SEQ_REPLY_ID.NEXTVAL, 1, 3, '안녕하세요', NULL,DEFAULT);
INSERT INTO TB_REPLY
VALUES (SEQ_REPLY_ID.NEXTVAL, 1, 2, '반갑습니다', NULL,DEFAULT);

INSERT INTO TB_POST_LIKE
VALUES (2, 3);
INSERT INTO TB_POST_LIKE
VALUES (1, 3);
INSERT INTO TB_POST_LIKE
VALUES (2, 2);

-- MEMBER_ID 1번 (3개)
INSERT INTO TB_TODO VALUES (SEQ_TODO_ID.NEXTVAL, 1, TO_DATE('2025-06-02', 'YYYY-MM-DD'), TO_DATE('2025-06-30', 'YYYY-MM-DD'), 'DIET', 'A', 3, 2000, 65);
INSERT INTO TB_TODO VALUES (SEQ_TODO_ID.NEXTVAL, 1, TO_DATE('2025-06-08', 'YYYY-MM-DD'), TO_DATE('2025-06-30', 'YYYY-MM-DD'), 'STRENGTH', 'B', 4, 2100, 70);
INSERT INTO TB_TODO VALUES (SEQ_TODO_ID.NEXTVAL, 1, TO_DATE('2025-06-15', 'YYYY-MM-DD'), TO_DATE('2025-06-30', 'YYYY-MM-DD'), 'ENDURANCE', 'C', 2, 2200, 68);

-- MEMBER_ID 2번 (4개)
INSERT INTO TB_TODO VALUES (SEQ_TODO_ID.NEXTVAL, 2, TO_DATE('2025-06-03', 'YYYY-MM-DD'), TO_DATE('2025-06-20', 'YYYY-MM-DD'), 'DIET', 'A', 5, 1800, 60);
INSERT INTO TB_TODO VALUES (SEQ_TODO_ID.NEXTVAL, 2, TO_DATE('2025-06-10', 'YYYY-MM-DD'), TO_DATE('2025-06-25', 'YYYY-MM-DD'), 'MAINTENANCE', 'B', 3, 1900, 62);
INSERT INTO TB_TODO VALUES (SEQ_TODO_ID.NEXTVAL, 2, TO_DATE('2025-06-15', 'YYYY-MM-DD'), TO_DATE('2025-06-28', 'YYYY-MM-DD'), 'DIET', 'A', 6, 2000, 61);
INSERT INTO TB_TODO VALUES (SEQ_TODO_ID.NEXTVAL, 2, TO_DATE('2025-06-20', 'YYYY-MM-DD'), TO_DATE('2025-06-30', 'YYYY-MM-DD'), 'DIET', 'C', 4, 2000, 59);

-- MEMBER_ID 3번 (2개)
INSERT INTO TB_TODO VALUES (SEQ_TODO_ID.NEXTVAL, 3, TO_DATE('2025-06-05', 'YYYY-MM-DD'), TO_DATE('2025-06-25', 'YYYY-MM-DD'), 'STRENGTH', 'A', 2, 2500, 75);
INSERT INTO TB_TODO VALUES (SEQ_TODO_ID.NEXTVAL, 3, TO_DATE('2025-06-22', 'YYYY-MM-DD'), TO_DATE('2025-06-29', 'YYYY-MM-DD'), 'MAINTENANCE', 'B', 3, 2400, 74);

-- MEMBER_ID 4번 (1개)
INSERT INTO TB_TODO VALUES (SEQ_TODO_ID.NEXTVAL, 4, TO_DATE('2025-05-28', 'YYYY-MM-DD'), TO_DATE('2025-06-15', 'YYYY-MM-DD'), 'ENDURANCE', 'C', 4, 2100, 68);

-- MEMBER_ID 5번 (4개, 1개는 지난달)
INSERT INTO TB_TODO VALUES (SEQ_TODO_ID.NEXTVAL, 5, TO_DATE('2025-05-30', 'YYYY-MM-DD'), TO_DATE('2025-06-20', 'YYYY-MM-DD'), 'DIET', 'A', 3, 2000, 67);
INSERT INTO TB_TODO VALUES (SEQ_TODO_ID.NEXTVAL, 5, TO_DATE('2025-06-02', 'YYYY-MM-DD'), TO_DATE('2025-06-15', 'YYYY-MM-DD'), 'STRENGTH', 'C', 5, 2300, 69);
INSERT INTO TB_TODO VALUES (SEQ_TODO_ID.NEXTVAL, 5, TO_DATE('2025-06-10', 'YYYY-MM-DD'), TO_DATE('2025-06-25', 'YYYY-MM-DD'), 'MAINTENANCE', 'B', 3, 2100, 68);
INSERT INTO TB_TODO VALUES (SEQ_TODO_ID.NEXTVAL, 5, TO_DATE('2025-06-22', 'YYYY-MM-DD'), TO_DATE('2025-06-29', 'YYYY-MM-DD'), 'DIET', 'C', 4, 1900, 66);
