INSERT INTO TB_MENU
VALUES (SEQ_MENU_ID.NEXTVAL, '메뉴1', 10, 10, 10, 'RICE');
INSERT INTO TB_MENU
VALUES (SEQ_MENU_ID.NEXTVAL, '메뉴2', 15, 10, 20, 'SOUPS');

INSERT INTO TB_MEMBER
VALUES (1, 'test_1@gmail.com', '$2a$10$fIfhtxnZYd2hdA9S5x38Deq2HGotuk.ASz0DQe8sQz82umYm7OYMO', '뽀리', 'F', sysdate, '010-1234-5678', sysdate, 'Y');
INSERT INTO TB_MEMBER
VALUES (2, 'test_2@gmail.com', '$2a$10$fIfhtxnZYd2hdA9S5x38Deq2HGotuk.ASz0DQe8sQz82umYm7OYMO', '재롱이', 'M', sysdate, '010-1111-2222', sysdate, 'Y');
INSERT INTO TB_MEMBER
VALUES (3, 'test_3@gmail.com', '$2a$10$fIfhtxnZYd2hdA9S5x38Deq2HGotuk.ASz0DQe8sQz82umYm7OYMO', '가나', 'M', sysdate, '010-1311-2222', sysdate, 'Y');
INSERT INTO TB_MEMBER
VALUES (4, 'test_4@gmail.com', '$2a$10$fIfhtxnZYd2hdA9S5x38Deq2HGotuk.ASz0DQe8sQz82umYm7OYMO', '다라', 'F', sysdate, '010-1611-2222', sysdate, 'Y');

INSERT INTO TB_BLOG
VALUES (1, 1, '저는 뽀리입니다. 꽤 귀엽구요\n잘 부탁합니다.', 120);
INSERT INTO TB_BLOG
VALUES (2, 2, '저는 재롱이입니다. 굉장히 싸납구요\n조심하세요.', 57);
INSERT INTO TB_BLOG
VALUES (3, 3, '저는 담비입니다.\n구운게 아니라 원래 색깔입니다.', 1000);
INSERT INTO TB_BLOG
VALUES (4, 4, '저는 환희입니다. \n항상 감사하구요.\n주인만 물어요.\n센척 엄청합니다.', 650);

INSERT INTO TB_MEMBER_DETAIL
VALUES (1, 164, 66);
INSERT INTO TB_MEMBER_DETAIL
VALUES (2, 170, 70);
INSERT INTO TB_MEMBER_DETAIL
VALUES (3, 181, 85);
INSERT INTO TB_MEMBER_DETAIL
VALUES (4, 155, 45);

INSERT INTO TB_FOLLOW
VALUES (1, 2);
INSERT INTO TB_FOLLOW
VALUES (1, 3);
INSERT INTO TB_FOLLOW
VALUES (1, 4);
INSERT INTO TB_FOLLOW
VALUES (2, 1);
INSERT INTO TB_FOLLOW
VALUES (3, 1);
INSERT INTO TB_FOLLOW
VALUES (4, 1);

INSERT INTO TB_MEMBER_DETAIL
VALUES (1, 160, 43);

INSERT INTO TB_MEMBER_DETAIL
VALUES (2, 178, 67);

-- 운동 공공데이터 (CSV)
INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (1, '108배', 2, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (2, 'AB 롤아웃', 8, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (3, 'TRX 운동', 7, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (4, 'wty운동', 7, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (5, 'W익스텐션', 4, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (6, '걷기', 3, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (7, '검도', 6, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (8, '게이트볼', 3, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (9, '계단내려가기', 3, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (10, '계단오르기', 8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (11, '고블릿 스쿼트', 5.5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (12, '고전무용', 6, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (13, '고정식 자전거', 5.5, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (14, '골프', 4.8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (15, '국민체조', 3.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (16, '권투펀칭', 6, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (17, '기체조', 4.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (18, '낚시', 3, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (19, '난타', 3.8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (20, '노르딕워킹', 6, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (21, '농구슈팅 연습', 4.5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (22, '농구시합', 8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (23, '다이어트 댄스', 4.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (24, '다트', 2.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (25, '달리기', 7, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (26, '당구', 2.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (27, '대청소', 3, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (28, '댄스스포츠', 5.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (29, '덤벨 바디 로테이션', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (30, '덤벨 숄더프레스', 5.5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (31, '덤벨 프레스', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (32, '덤벨 플라이', 5.5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (33, '덩키킥', 7, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (34, '데드 리프트', 5.5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (35, '데드버그', 4, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (36, '뒤로 걷기', 3, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (37, '등산', 7, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (38, '디스코 댄스', 7.8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (39, '딥스', 5.5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (40, '뛰기', 7, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (41, '라인댄스', 7.8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (42, '라켓볼연습', 7, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (43, '러시안트위스트', 4, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (44, '런닝', 7, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (45, '런닝머신', 6, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (46, '런지', 3.8, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (47, '레그 레이즈', 5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (48, '레그 익스텐션', 5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (49, '레그 컬', 5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (50, '레그 킥 백', 5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (51, '레그 프레스', 5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (52, '레터럴 레이즈', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (53, '레프팅', 5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (54, '렛풀다운', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (55, '로드바이크', 8.5, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (56, '로프운동', 6, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (57, '루마니안 데드리프트', 5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (58, '리버스 컬', 5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (59, '리버스 팩 덱 플라이', 4, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (60, '마라톤', 9, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (61, '마운틴 클라이머', 7, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (62, '마이마운틴', 5.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (63, '맨발걷기', 4.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (64, '맨손 줄넘기', 7, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (65, '모던댄스', 4.8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (66, '모래주머니 차고 걷기', 6.8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (67, '바벨 숄더프레스', 5.5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (68, '바벨 스쿼트', 6, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (69, '발레', 5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (70, '방송댄스', 7, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (71, '배구연습', 4, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (72, '배드민턴', 4.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (73, '백 스쿼트', 6, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (74, '백 익스텐션', 3.5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (75, '밸리댄스', 4.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (76, '버드독', 3.8, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (77, '버피테스트', 7, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (78, '번지피지오', 5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (79, '벤치 프레스', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (80, '벤치딥스', 3, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (81, '벤트 오버 레터럴 레이즈', 5.5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (82, '벤트 오버 바벨 로우', 5.5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (83, '벽 스쿼트', 5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (84, '복근운동', 3.8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (85, '복싱', 7.8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (86, '볼링', 3, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (87, '브릿지', 3.5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (88, '빠르게 걷기', 6, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (89, '사이드 런지', 5.5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (90, '사이드 레그레이즈', 4, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (91, '사이드 레터럴 레이즈', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (92, '사이드 밴드', 3.5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (93, '사이드 크런치', 4, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (94, '사이드 플랭크', 3.8, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (95, '사이클론', 7, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (96, '산악자전거', 8.5, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (97, '산책', 4, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (98, '산행', 4, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (99, '살사댄스', 4.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (100, '새천년체조', 3.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (101, '세차', 3, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (102, '수상스키', 6, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (103, '수영(IM)', 8, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (104, '수영(배영)', 8, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (105, '수영(자유영)', 6.1, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (106, '수영(접영)', 11, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (107, '수영(평영)', 5.3, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (108, '수중 에어로빅', 4, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (109, '스케이팅', 7, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (110, '스쿼시', 12, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (111, '스쿼트', 5.5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (112, '스쿼트 덤벨 프레스', 7, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (113, '스크린골프', 4, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (114, '스키', 6, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (115, '스키머신', 6.8, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (116, '스탠딩 카프 레이즈', 5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (117, '스텝밀', 7, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (118, '스텝박스', 5.5, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (119, '스티프 레그 데드리프트', 8, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (120, '스포츠댄스', 5.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (121, '스포츠클라이밍', 7, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (122, '스플릿 스쿼트', 5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (123, '슬로우버피', 5.5, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (124, '승마', 5.8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (125, '시티드 니업', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (126, '시티드 로우', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (127, '실내 스케이팅', 7, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (128, '실내 자전거', 5.5, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (129, '씨름', 6, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (130, '아령들기', 5.5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (131, '아이스하키', 8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (132, '아쿠아로빅', 4, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (133, '악력기 운동', 1.3, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (134, '앉아서 다리들기', 2.5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (135, '암벽등반', 11, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (136, '암워킹', 6, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (137, '암풀다운', 4, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (138, '야구 캐치볼', 2.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (139, '양팔벌려 제자리 뛰기(PT체조)', 3, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (140, '어시스트 풀업', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (141, '에어로빅', 6.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (142, '에어로빅', 6, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (143, '와이드 스쿼트', 5.5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (144, '와일드 런지', 5.5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (145, '요가', 2.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (146, '운동장 걷기', 4.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (147, '워킹', 4.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (148, '워킹런지', 5.5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (149, '원 암 덤벨로우', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (150, '월볼샷', 6, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (151, '윈드서핑', 5, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (152, '윗몸일으키기', 3.8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (153, '유도', 10, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (154, '유연체조', 3.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (155, '이두 컬', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (156, '인라인스케이트', 5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (157, '인클라인 벤치 프레스', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (158, '인터벌 런닝', 8, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (159, '일립티컬', 6, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (160, '자유수영', 6, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (161, '자전거', 7, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (162, '재즈댄스', 4.8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (163, '재즈사이즈', 6, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (164, '점프 버피테스트', 8.5, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (165, '점프 스쿼트', 6, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (166, '점핑운동', 4.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (167, '제기차기', 3, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (168, '제자리 걷기', 2, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (169, '제자리뛰기', 5.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (170, '조깅', 7, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (171, '조정(로잉머신)', 4.8, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (172, '족구', 5.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (173, '주짓수', 5.3, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (174, '줄넘기', 8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (175, '줌바댄스', 5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (176, '짐볼운동', 3.8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (177, '천국의계단', 8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (178, '철봉매달리기', 3.8, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (179, '체스트 프레스', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (180, '축구 프리킥 차기', 7, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (181, '축구시합', 10, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (182, '축구연습', 7, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (183, '컨벤셔널 데드리프트', 8, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (184, '케이블 크로스 오버', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (185, '케틀벨', 5.5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (186, '크런치', 5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (187, '크로스 크런치', 4.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (188, '크로스 핏', 8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (189, '킥 백', 5, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (190, '킥복싱', 10, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (191, '탁구', 4, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (192, '태권도', 10, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (193, '태극권', 4, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (194, '태보', 7, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (195, '탱고', 5.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (196, '턱걸이', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (197, '테니스', 7, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (198, '트라이셉스 익스텐션', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (199, '트라이셉스 푸시 다운', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (200, '트래킹', 5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (201, '트랙걷기', 4.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (202, '트램폴린', 4.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (203, '트위스트 댄스', 4.8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (204, '트위스트 런', 5, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (205, '파워워킹', 6, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (206, '파크골프', 4.3, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (207, '팔굽혀펴기', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (208, '패들보드', 6, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (209, '팩 덱 플라이', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (210, '펙덱 플라이', 5.5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (211, '펜싱', 6, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (212, '포크댄스', 7.8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (213, '폴댄스', 5.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (214, '폼롤러', 3, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (215, '푸쉬업', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (216, '풀 스쿼트', 6, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (217, '풀업 - 상지(어깨)', 3.8, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (218, '풀업(턱걸이)', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (219, '풋살', 8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (220, '프론트 레이즈', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (221, '프론트 풀다운', 4, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (222, '프리다이빙', 7, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (223, '프리테니스', 7, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (224, '플라멩고', 4.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (225, '플랭크', 3.8, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (226, '플로터킥', 5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (227, '필라테스', 5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (228, '하이킹', 6, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (229, '하프마라톤', 9, 'CARDIO');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (230, '할로우 보디홀드', 3, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (231, '해머 컬', 5, 'UPPER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (232, '행잉 레그레이즈', 10, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (233, '훌라후프', 5.5, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (234, '훌라후프', 4, 'LIFE');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (235, '힙 쓰러스트', 6, 'LOWER');

INSERT INTO TB_EXERCISE (EXERCISE_ID, NAME, MET, CATEGORY)
VALUES (236, '힙 어브덕션', 5, 'LOWER');

INSERT INTO TB_BOARD
VALUES (SEQ_BOARD_ID.NEXTVAL,
        '부산 해운대 가자',
        '이번 부산 해운대에서 선팅을 하기 위해서 몸을 만들기 시작했습니다.',
        DEFAULT,
        SYSDATE,
        2
        );

INSERT INTO TB_IMAGE
VALUES ('부산해운대.JPG', '7fa8b12a-d51e-4c4c-bfd4-9d9b6eab9f7e.JPG', 1);
INSERT INTO TB_IMAGE
VALUES ('파라솔.JPG', '7fa8b12a-d51e-4c4c-bfd4-9d9b6eab9f7e.JPG', 1);

INSERT INTO TB_BOARD
VALUES (SEQ_BOARD_ID.NEXTVAL,
        '20년만에 처음 다이어트',
        '19살까지 살이 찌지 않다가 20살때 급격히 식욕이 늘어나면서 10kg이 증가하였습니다.',
        DEFAULT,
        SYSDATE,
        2
        );

INSERT INTO TB_IMAGE
VALUES ('헬스장1일차.JPG', '7fa8b12a-d51e-4c4c-bfd4-9d9b6eab9f7e.JPG', 2);

INSERT INTO TB_BOARD
VALUES (SEQ_BOARD_ID.NEXTVAL,
        '인생 첫 바디프로필',
        '이번에 5개월 동안 식단과 운동을 병행하여 인생에서 처음으로 바디프로필을 찍어봤습니다.',
        DEFAULT,
        SYSDATE,
        1
        );

INSERT INTO TB_IMAGE
VALUES ('식단 1일차.JPG', '7fa8b12a-d51e-4c4c-bfd4-9d9b6eab9f7e.JPG', 3);
INSERT INTO TB_IMAGE
VALUES ('식단 2일차.JPG', '7fa8b12a-d51e-4c4c-bfd4-9d9b6eab9f7e.JPG', 3);
INSERT INTO TB_IMAGE
VALUES ('헬스장.JPG', '7fa8b12a-d51e-4c4c-bfd4-9d9b6eab9f7e.JPG', 3);

INSERT INTO TB_BOARD
VALUES (SEQ_BOARD_ID.NEXTVAL,
        '두번째 바디프로필은 할만 하네',
        '두번째라고 식단과 운동을 하는것에는 어렵지 않았는데, 운동에 대한 회의감을 견디는게 조금 힘들었습니다.',
        DEFAULT,
        SYSDATE,
        1
        );

INSERT INTO TB_IMAGE
VALUES ('식단.JPG', '7fa8b12a-d51e-4c4c-bfd4-9d9b6eab9f7e.JPG', 4);
INSERT INTO TB_IMAGE
VALUES ('헬스장.JPG', '7fa8b12a-d51e-4c4c-bfd4-9d9b6eab9f7e.JPG', 4);

INSERT INTO TB_BOARD_LIKE
VALUES (2, 3);

INSERT INTO TB_BOARD_LIKE
VALUES (1, 3);

INSERT INTO TB_BOARD_LIKE
VALUES (2, 2);
