DROP TABLE TB_REPLY_LIKE;
DROP TABLE TB_BOARD_LIKE;
DROP TABLE TB_IMAGE;
DROP TABLE TB_REPLY;
DROP TABLE TB_MENU_DETAIL;
DROP TABLE TB_DAILY_MENU;
DROP TABLE TB_EXERCISE_DETAIL;
DROP TABLE TB_DAILY_EXERCISE;
DROP TABLE TB_ALARM;
DROP TABLE TB_FOLLOW;
DROP TABLE TB_TODO;
DROP TABLE TB_BOARD;
DROP TABLE TB_BLOG;
DROP TABLE TB_WITHDRAW;
DROP TABLE TB_MEMBER_DETAIL;
DROP TABLE TB_MENU;
DROP TABLE TB_EXERCISE;
DROP TABLE TB_MEMBER;

DROP SEQUENCE SEQ_BOARD_ID;
DROP SEQUENCE SEQ_REPLY_ID;
DROP SEQUENCE SEQ_MEMBER_ID;
DROP SEQUENCE SEQ_NOTICE_ID;
DROP SEQUENCE SEQ_TODO_ID;
DROP SEQUENCE SEQ_DAILY_MENU_ID;
DROP SEQUENCE SEQ_MENU_ID;
DROP SEQUENCE SEQ_DAILY_EXERCISE_ID;
DROP SEQUENCE SEQ_EXERCISE_ID;
DROP SEQUENCE SEQ_BLOG_ID;

CREATE TABLE TB_MEMBER
(
    MEMBER_ID  NUMBER                               NOT NULL,
    EMAIL      VARCHAR2(255) UNIQUE                 NOT NULL,
    PASSWORD   VARCHAR2(255)                        NOT NULL,
    NICKNAME   VARCHAR2(50) UNIQUE                  NOT NULL,
    GENDER     CHAR(1) CHECK (GENDER IN ('M', 'F')) NOT NULL,
    BIRTH_AT   DATE                                 NOT NULL,
    PHONE      VARCHAR2(13) UNIQUE                  NOT NULL,
    CREATED_AT DATE    DEFAULT SYSDATE              NOT NULL,
    IS_DELETED     CHAR(1) DEFAULT 'Y'                  NOT NULL,
    CONSTRAINT PK_TB_MEMBER PRIMARY KEY (MEMBER_ID)
);

CREATE TABLE TB_BLOG
(
    BLOG_ID   NUMBER                  NOT NULL,
    MEMBER_ID NUMBER                  NOT NULL,
    INTRODUCE VARCHAR2(255),
    GRADE     NUMBER        DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TB_BLOG PRIMARY KEY (BLOG_ID),
    CONSTRAINT FK_TB_MEMBER_TO_TB_BLOG_1 FOREIGN KEY (MEMBER_ID) REFERENCES TB_MEMBER (MEMBER_ID)
);

CREATE TABLE TB_MENU
(
    MENU_ID       NUMBER                                                           NOT NULL,
    NAME          VARCHAR2(100)                                                    NOT NULL,
    CALORIE       NUMBER                                                           NOT NULL,
    CARBOHYDRATE  NUMBER                                                           NOT NULL,
    PROTEIN       NUMBER                                                           NOT NULL,
    CATEGORY VARCHAR2(30) CHECK (CATEGORY IN ('RICE', 'SIDES', 'SOUPS')) NOT NULL,
    CONSTRAINT PK_TB_MENU PRIMARY KEY (MENU_ID)
);

CREATE TABLE TB_EXERCISE
(
    EXERCISE_ID       NUMBER                                                                         NOT NULL,
    NAME              VARCHAR2(100)                                                                  NOT NULL,
    MET               NUMBER                                                                         NOT NULL,
    CATEGORY VARCHAR2(50) CHECK (CATEGORY IN ('UPPER', 'LOWER', 'CARDIO', 'LIFE')) NOT NULL,
    CONSTRAINT PK_TB_EXERCISE PRIMARY KEY (EXERCISE_ID)
);

CREATE TABLE TB_TODO
(
    TODO_ID     NUMBER                                                                           NOT NULL,
    MEMBER_ID   NUMBER                                                                           NOT NULL,
    STARTED_AT  DATE                                                                             NOT NULL,
    ENDED_AT    DATE                                                                             NOT NULL,
    PURPOSE     VARCHAR2(30) CHECK (PURPOSE IN ('ENDURANCE', 'STRENGTH', 'MAINTENANCE', 'DIET')) NOT NULL,
    CATEGORY    VARCHAR2(8)                                                                      NOT NULL,
    DAY_KCAL    NUMBER,
    DAY_REPEAT  NUMBER,
    TDEE        NUMBER,
    GOAL_WEIGHT NUMBER,
    CONSTRAINT PK_TB_TODO PRIMARY KEY (TODO_ID),
    CONSTRAINT FK_TB_MEMBER_TO_TB_TODO_1 FOREIGN KEY (MEMBER_ID) REFERENCES TB_MEMBER (MEMBER_ID) ON DELETE CASCADE
);

CREATE TABLE TB_DAILY_MENU
(
    DAILY_MENU_ID NUMBER NOT NULL,
    TODO_ID       NUMBER NOT NULL,
    DAY_NO        NUMBER NOT NULL,
    CONSTRAINT PK_TB_DAILY_MENU PRIMARY KEY (DAILY_MENU_ID),
    CONSTRAINT FK_TB_TODO_TO_TB_DAILY_MENU_1 FOREIGN KEY (TODO_ID) REFERENCES TB_TODO (TODO_ID) ON DELETE CASCADE
);

CREATE TABLE TB_DAILY_EXERCISE
(
    DAILY_EXERCISE_ID NUMBER NOT NULL,
    TODO_ID           NUMBER NOT NULL,
    DAY_NO            NUMBER NOT NULL,
    CONSTRAINT PK_TB_DAILY_EXERCISE PRIMARY KEY (DAILY_EXERCISE_ID),
    CONSTRAINT FK_TB_TODO_TO_TB_DAILY_EXERCISE_1 FOREIGN KEY (TODO_ID) REFERENCES TB_TODO (TODO_ID) ON DELETE CASCADE
);

CREATE TABLE TB_MENU_DETAIL
(
    DAILY_MENU_ID NUMBER NOT NULL,
    MENU_ID       NUMBER NOT NULL,
    CONSTRAINT FK_TB_DAILY_MENU_TO_TB_MENU_DETAIL_1 FOREIGN KEY (DAILY_MENU_ID) REFERENCES TB_DAILY_MENU (DAILY_MENU_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TB_MENU_TO_TB_MENU_DETAIL_1 FOREIGN KEY (MENU_ID) REFERENCES TB_MENU (MENU_ID)
);

CREATE TABLE TB_EXERCISE_DETAIL
(
    DAILY_EXERCISE_ID NUMBER NOT NULL,
    EXERCISE_ID       NUMBER NOT NULL,
    CONSTRAINT FK_TB_DAILY_EXERCISE_TO_TB_EXERCISE_DETAIL_1 FOREIGN KEY (DAILY_EXERCISE_ID) REFERENCES TB_DAILY_EXERCISE (DAILY_EXERCISE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TB_EXERCISE_TO_TB_EXERCISE_DETAIL_1 FOREIGN KEY (EXERCISE_ID) REFERENCES TB_EXERCISE (EXERCISE_ID)
);

CREATE TABLE TB_BOARD
(
    BOARD_ID      NUMBER                                                                                  NOT NULL,
    TITLE         VARCHAR2(150)                                                                           NOT NULL,
    CONTENT VARCHAR2(1500),
    CATEGORY      VARCHAR2(20) DEFAULT 'ALL' CHECK (CATEGORY IN ('ALL', 'DIET', 'STRENGTH', 'ENDURANCE')) NOT NULL,
    CREATED_AT    DATE         DEFAULT SYSDATE                                                            NOT NULL,
    BLOG_ID     NUMBER                                                                                  NOT NULL,
    CONSTRAINT PK_TB_BOARD PRIMARY KEY (BOARD_ID),
    CONSTRAINT FK_TB_MEMBER_TO_TB_BOARD_1 FOREIGN KEY (BLOG_ID) REFERENCES TB_BLOG (BLOG_ID)
);

CREATE TABLE TB_IMAGE
(
    ORIGIN_NAME VARCHAR2(255) NOT NULL,
    CHANGE_NAME VARCHAR2(255) NOT NULL,
    BOARD_ID    NUMBER        NOT NULL,
    CONSTRAINT FK_TB_BOARD_TO_TB_IMAGE_1 FOREIGN KEY (BOARD_ID) REFERENCES TB_BOARD (BOARD_ID) ON DELETE CASCADE
);

CREATE TABLE TB_REPLY
(
    REPLY_ID        NUMBER               NOT NULL,
    BOARD_ID        NUMBER               NOT NULL,
    MEMBER_ID       NUMBER               NOT NULL,
    CONTENT   VARCHAR2(1500)       NOT NULL,
    PARENT_ID NUMBER,
    REPLIED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TB_REPLY PRIMARY KEY (REPLY_ID),
    CONSTRAINT FK_TB_BOARD_TO_TB_REPLY_1 FOREIGN KEY (BOARD_ID) REFERENCES TB_BOARD (BOARD_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TB_MEMBER_TO_TB_REPLY_2 FOREIGN KEY (MEMBER_ID) REFERENCES TB_MEMBER (MEMBER_ID)
);

CREATE TABLE TB_REPLY_LIKE
(
    MEMBER_ID NUMBER NOT NULL,
    REPLY_ID  NUMBER NOT NULL,
    CONSTRAINT FK_TB_MEMBER_TO_TB_REPLY_LIKE_1 FOREIGN KEY (MEMBER_ID) REFERENCES TB_MEMBER (MEMBER_ID),
    CONSTRAINT FK_TB_REPLY_TO_TB_REPLY_LIKE_1 FOREIGN KEY (REPLY_ID) REFERENCES TB_REPLY (REPLY_ID) ON DELETE CASCADE
);

CREATE TABLE TB_BOARD_LIKE
(
    MEMBER_ID NUMBER NOT NULL,
    BOARD_ID  NUMBER NOT NULL,
    CONSTRAINT FK_TB_BOARD_TO_TB_BOARD_LIKE_1 FOREIGN KEY (BOARD_ID) REFERENCES TB_BOARD (BOARD_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TB_MEMBER_TO_TB_BOARD_LIKE_1 FOREIGN KEY (MEMBER_ID) REFERENCES TB_MEMBER (MEMBER_ID)
);

CREATE TABLE TB_ALARM
(
    NOTICE_ID          NUMBER                                                               NOT NULL,
    CONTENT     VARCHAR2(100)                                                        NOT NULL,
    CATEGORY           VARCHAR2(30) CHECK (CATEGORY IN ('REPLY', 'TODO', 'FOLLOW', 'LIKE')) NOT NULL,
    CREATED_AT         DATE DEFAULT SYSDATE                                                 NOT NULL,
    RECEIVER_MEMBER_ID NUMBER                                                               NOT NULL,
    SENDER_MEMBER_ID   NUMBER                                                               NOT NULL,
    CONSTRAINT PK_TB_ALARM PRIMARY KEY (NOTICE_ID),
    CONSTRAINT FK_TB_MEMBER_TO_TB_ALARM_1 FOREIGN KEY (RECEIVER_MEMBER_ID) REFERENCES TB_MEMBER (MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TB_MEMBER_TO_TB_ALARM_2 FOREIGN KEY (SENDER_MEMBER_ID) REFERENCES TB_MEMBER (MEMBER_ID) ON DELETE CASCADE
);

CREATE TABLE TB_FOLLOW
(
    FOLLOWED_MEMBER_ID NUMBER NOT NULL,
    FOLLOWER_MEMBER_ID NUMBER NOT NULL,
    CONSTRAINT FK_TB_MEMBER_TO_TB_FOLLOW_1 FOREIGN KEY (FOLLOWED_MEMBER_ID) REFERENCES TB_MEMBER (MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TB_MEMBER_TO_TB_FOLLOW_2 FOREIGN KEY (FOLLOWER_MEMBER_ID) REFERENCES TB_MEMBER (MEMBER_ID) ON DELETE CASCADE
);

CREATE TABLE TB_MEMBER_DETAIL
(
    MEMBER_ID NUMBER NOT NULL,
    HEIGHT    NUMBER NOT NULL,
    WEIGHT    NUMBER NOT NULL,
    CONSTRAINT PK_TB_MEMBER_DETAIL PRIMARY KEY (MEMBER_ID),
    CONSTRAINT FK_TB_MEMBER_TO_TB_MEMBER_DETAIL_1 FOREIGN KEY (MEMBER_ID) REFERENCES TB_MEMBER (MEMBER_ID)
);

CREATE TABLE TB_WITHDRAW
(
    MEMBER_ID     NUMBER               NOT NULL,
    REASON_SELECT VARCHAR2(255),
    REASON_INPUT  VARCHAR2(3000),
    WITHDRAW_AT   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TB_WITHDRAW PRIMARY KEY (MEMBER_ID),
    CONSTRAINT FK_TB_MEMBER_TO_TB_WITHDRAW_1 FOREIGN KEY (MEMBER_ID) REFERENCES TB_MEMBER (MEMBER_ID)
);

CREATE SEQUENCE SEQ_BOARD_ID NOCACHE;
CREATE SEQUENCE SEQ_REPLY_ID NOCACHE;
CREATE SEQUENCE SEQ_MEMBER_ID NOCACHE;
CREATE SEQUENCE SEQ_NOTICE_ID NOCACHE;
CREATE SEQUENCE SEQ_TODO_ID NOCACHE;
CREATE SEQUENCE SEQ_DAILY_MENU_ID NOCACHE;
CREATE SEQUENCE SEQ_MENU_ID NOCACHE;
CREATE SEQUENCE SEQ_DAILY_EXERCISE_ID NOCACHE;
CREATE SEQUENCE SEQ_EXERCISE_ID NOCACHE;
CREATE SEQUENCE SEQ_BLOG_ID NOCACHE;